#Specify a base image
FROM node:11.5.0-alpine  
WORKDIR '/app'

#Install some dependencies
COPY ./package.json ./
RUN npm install
RUN chmod +x ./node_modules/.bin/react-scripts
COPY . .

#Default command
CMD ["npm", "run", "start"]