language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t phoenixqnxt/react-test-ly -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true phoenixqnxt/react-test-ly npm test  

after_success:
  - docker build -t phoenixqnxt/multi-client-ly ./client
  - docker build -t phoenixqnxt/multi-nginx-ly ./nginx
  - docker build -t phoenixqnxt/multi-server-ly ./server
  - docker build -t phoenixqnxt/multi-worker-ly ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these images and push them to docker hub
  - docker push phoenixqnxt/multi-client-ly
  - docker push phoenixqnxt/multi-nginx-ly
  - docker push phoenixqnxt/multi-server-ly 
  - docker push phoenixqnxt/multi-worker-ly



# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: multi-docker-ly
#   env: MultiDockerLy-env
#   bucket_name: elasticbeanstalk-us-east-2-214665640462
#   bucket_path: docker-multi-ly
#   on:
#     branch: master 
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY